# Generated by Django 4.1.7 on 2023-03-30 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('categorie', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('description', models.CharField(default='This product has no description', max_length=10000)),
                ('rebate', models.IntegerField()),
            ],
        ),
    ]
