# Generated by Django 4.1.7 on 2023-03-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='no_of_likes',
            field=models.IntegerField(default=0),
        ),
    ]
